//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSO.Archive.WebApp {
    
    
    public partial class Search {
        
        /// <summary>
        /// performanceBasicSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel performanceBasicSearch;
        
        /// <summary>
        /// PerformanceSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BSO.Archive.WebApp.Controls.PerformanceSearch PerformanceSearch;
        
        /// <summary>
        /// ArtistSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BSO.Archive.WebApp.Controls.ArtistSearch ArtistSearch;
        
        /// <summary>
        /// RepertoireSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BSO.Archive.WebApp.Controls.RepertoireSearch RepertoireSearch;
        
        /// <summary>
        /// SearchID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField SearchID;
        
        /// <summary>
        /// MaxSearchResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MaxSearchResults;
        
        /// <summary>
        /// EmailForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BSO.Archive.WebApp.Controls.EmailForm EmailForm;
        
        /// <summary>
        /// SearchInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BSO.Archive.WebApp.Controls.SearchInfo SearchInfo;
    }
}
